((define (func a b) 
        (-> int int int) 
        (if (= a 0)
            (if (= a 0)
                (func (- a 1) (+ b 1))
                b)
            (if (= a 0)
                (func (- a 1) (+ b 1))
                b)))
(print (func 5 4))))
